version: '3.8'

services:

  main:
    image: ${LOCAL_DOCKER_IMAGE}

    working_dir: /home/docky/workdir/tutorials

    environment:
        - PROJECT_NAME=${PROJECT_NAME}
        - PYTHONPATH=/home/docky/workdir/tutorials

    command: sh -c "yarpserver --write & yarprun --server /root --log & terminator"
